### ISSUE TITLE
Create wireframe for UI of editor based on WAI ATAG Editor UI.

### ISSUE THREAD

**Issue by dmundra** [GSA/openacr#110]
This is to show what the future editor tool could look like for OPATs.

**Comment by mgifford** [comment]
I started with just pulling out the text - https://github.com/GSA/open-product-accessibility-template/wiki/Possible-Walk-through-for-the-editor-interface

**Comment by mgifford** [comment]
I basically just changed the text here to help give a sense of it

![Screen Shot 2021-08-13 at 9 21 37 AM](https://user-images.githubusercontent.com/116832/129363860-acc16464-7f46-4e3b-a5cd-fca544631d95.png)

Also, noted that there is a new more modern UI that the W3C is testing out for the WCAG-EM so built an [alternative based on that too](https://github.com/GSA/open-product-accessibility-template/wiki/Possible-Walk-through-for-the-editor-interface:-Proposed-2021-Interface).

**Comment by mgifford** [comment]
Very similar, but moving to https://github.com/w3c/wai-atag-report-tool

https://wai-atag-report-tool.netlify.app/

Which is a simpler framework that was used by HDV that allows us to build out a similar editor.
