### ISSUE TITLE
OPAT Editor should be able to output in YAML, Markdown & HTML

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#119]
Is it possible to include in the editor the option to download in YAML, but also Markdown & HTML.

Absolutely, we want to make the .yaml file to be the default people use, but we also want to have something that people can easily read.  

We can't assume that folks are going to all be able to install this code locally and follow the very simple CLI.md instructions.

**Comment by dmundra** [comment]
The file handling code needed to be separated from the string templating. Submitted PR for that and then I can call the function in the editor to generate the HTML and markdown without the file stuff.

**Comment by dmundra** [comment]
It appears that Handlebar and its dependency on `fs` is not working with rollup. I will try an alternate route to outputting HTML and Markdown.

**Comment by dmundra** [comment]
Building the HTML in Svelte is a better process and looks to be working so going to continue with that and get a pull request done.

**Comment by dmundra** [comment]
From PR:

> This is an initial version that recreate the handlebar templates in Svelte for Markdown and HTML. Will have to add to it when we add the chapters and table fields. For Markdown had to build up a string manually to get the correct spacing and line breaks.
