### ISSUE TITLE
List of OpenACRs (OPATs) on GitHub

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#136]
Right now there are a number of vendors who post their ACRs publicly. It is great to be able to go to sites like these and access the latest ACRs. Here are just a few great examples:
- https://www.ibm.com/able/product_accessibility
- https://cloudblogs.microsoft.com/industry-blog/government/2018/09/11/accessibility-conformance-reports/
- https://www.adobe.com/accessibility/compliance.html
- https://www.vmware.com/ca/help/accessibility.html
- https://www.oracle.com/corporate/accessibility/vpats.html#acrs-tab

Instead of linking to a page with a collection of PDF files, we should be pointing to a link to the git repository. 

We might need to structure a listing slightly differently to adjust to this, but when these shift to an OPAT format, there will be no reason not to simply link to a repository (on GitHub, GitLab or whatever) where either a product has it's ACR (Drupal may want to release it right with the rest of the source code) or as a corporate collection of all ACR.  

In anycase, it would be easy to start building a listing of which vendors are providing OPAT compatible ACRs with version control and start a page to start linking to them here (when it happens).

**Comment by dmundra** [comment]
Another one: https://www.instructure.com/canvas/accessibility

**Comment by mgifford** [comment]
I am thinking we can close this one. These are currently VPAT lists.
