### ISSUE TITLE
Guides for editor

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#142]
Aside from simply providing input, the OPAT Editor Tool can provide insights to the author to allow them to add additional context that might help support their product in a bid process.

- "notes" - "Any details or explanation about the product or the report." - however we could be more explicit here.  It is important for procurement officers to understand how accessibility is built into your software development process. 
- "evaluation_methods_used" - "Include a description of evaluation methods used to complete the OPAT for the product under test." - Please describe in detail how your ACR was built and maintained. Have you used both automated and manual tests? Have users with lived experience been involved in evaluating the project? Do you test critical workflows to see that they can be used by a wide variety of users? Have you included just public facing content or also authoring tools in your evaluation? 

We can hint at what evaluators should be looking for to move ACRs from comparing number of errors to comparing processes.

**Comment by farooqzakhilwal** [comment]
Mike to review with Danita

**Comment by mgifford** [comment]
https://gsa.github.io/openacr-editor/about#evaluation-evaluation-methods-used

I've put in "Please describe in detail how this report was created. What tools and processes were used. How many and what type of pages were evaluated, along with anythng else which would provide context." in the description.

There are some suggestions here we might want to bring in to overcome limitations in WCAG 2.0 - https://github.com/GSA/openacr/issues/236#issuecomment-995883503

We may need more user research to address this. Fortunately we have a form that we can engage people with.

**Comment by danid123** [comment]
Also, when I looked at [comparison tools UI](https://docs.google.com/document/d/1OP7wfc1ccpCQ6uo9Zdinrq1u53it64CLWS9XoYMMXcI/edit?usp=sharing), I discovered that the one way we could encourage vendors to fill out the notes information is to show how it will be viewed by the procurement officer. I think demonstrating how providing more information helps rather than hurts their bid will encourage vendors to provide optional information.
