### ISSUE TITLE
License/attribution

### ISSUE THREAD

**Issue by grugnog** [GSA/openacr#203]
- [x] We should make sure the [license](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document) is linked from the UI as well as the README
- [x] We should include the required W3C attribution (see page for language) in the UI as well as the README
- [x] We should link to the ART and WCAG-UI projects somewhere in the UI also (ART is already linked in the README)

**Comment by dmundra** [comment]
Made the changes as directed and also copied over some contributing text from OpenACR.
