### ISSUE TITLE
Selecting defaults for the chapter components and adding help text

### ISSUE THREAD

**Issue by dmundra** [GSA/openacr#211]
Discuss what we want the defaults to be after the forms for the chapters are built and adjusted to match desired structure.

Also add help text.

**Comment by dmundra** [comment]
@danid123 and @mgifford as part of this should I go ahead and make each criteria collapsible and default collapsed?

**Comment by mgifford** [comment]
I don't know. If it is collapsed, people will think they don't need to fill it in. This might be the case, but... What do you think @danid123 how do we best support our authors?
