### ISSUE TITLE
Add related OpenACRs

### ISSUE THREAD

**Issue by dmundra** [GSA/openacr#220]
Add related OpenACRs field to the editor and output to YAML, HTML, and Markdown. The field is will be a multi value URL version.

**Comment by dmundra** [comment]
Found solution from https://www.w3.org/WAI/eval/report-tool/evaluation/select-sample and also looked at the [code closely](https://github.com/w3c/wai-wcag-em-report-tool/blob/main/src/components/form/SampleInput/SampleInput.svelte) to see how the array is dynamically updated. See https://svelte.dev/tutorial/updating-arrays-and-objects for an example.

**Comment by mgifford** [comment]
I think that there might be a Safari problem that was brought in at an earlier commit.  It worked when I hadn't loaded the Drupal file.

I Load an yaml file

![Screen Shot with notice](https://user-images.githubusercontent.com/116832/146299141-667018b8-bb6d-483f-8883-c3ccf58e1345.png)

Looks good: 

![Screen Shot after it has loaded](https://user-images.githubusercontent.com/116832/146299203-46088a96-ce4f-43d1-be65-191a2f49f65d.png)

On the about page (something is missing):
![Screen Shot of about page](https://user-images.githubusercontent.com/116832/146299295-103c1ea6-2894-42a8-bc06-b3cde115c5f8.png)

Reloaded the about page (more is missing):
![Screen Shot of about page after refresh](https://user-images.githubusercontent.com/116832/146299342-75b8aee3-20f9-40a7-918c-e3c937d6245a.png)

Ok this definitely isn't right (nothing on other pages):
![Screen Shot This should be the AAA page](https://user-images.githubusercontent.com/116832/146299428-89adb888-2cd9-4a1e-90be-0a945060919b.png)

What the Inspector is showing me:
![Screen Shot with Dev mode](https://user-images.githubusercontent.com/116832/146299678-d06994c9-accb-427b-bf7f-d4aa0f74bcd7.png)

What's up?

**Comment by dmundra** [comment]
Good catch. Can you share that yamk file you used and also screenshot of the console from the inspector?

**Comment by dmundra** [comment]
@mgifford fixed it. I was not initializing the array when imported. Give it a try again when you can.
