### ISSUE TITLE
Change margin for "Results Choices" definition list

### ISSUE THREAD

**Issue by danid123** [GSA/openacr#221]
Change the margin for the definitions to 0px to help with eye tracking.

**Comment by mgifford** [comment]
Hey @danid123 is it possible to have a URL & screenshot? I think you mean https://gsa.github.io/openacr-editor/about but am not certain. @dmundra might well know based on that description but I don't.

**Comment by mgifford** [comment]
https://gsa.github.io/openacr-editor/

![Screen Shot in Overview for Result choices](https://user-images.githubusercontent.com/116832/148804135-4e72587a-43a1-4559-b79b-1642680be3a6.png)

**Comment by mgifford** [comment]
So moving from:

```
dd {
  margin-inline-start: 32px;
}
```

to

```
dd {
  margin-inline-start: 0;
}
```

in assets/_components/lists.css

![Screen Shot with 0 margins](https://user-images.githubusercontent.com/116832/148805086-d4d50765-7737-46fe-9009-e047e2ee92a3.png)

**Comment by danid123** [comment]
Yes that's correct. Thanks for the clarification @mgifford !

**Comment by danid123** [comment]
Can we also add margin-bottom: 12px; so that the definitions "chunk" better with their titles?

**Comment by dmundra** [comment]
Is the styling isolated to the 'Results choices" list? Or should this change be made to the glossary page as well?

**Comment by mgifford** [comment]
I'd think we'd want to be consistent. Here's what the Glossary would look like with that spacing.

```
dd {
  margin-inline-start: 0;
}

dd+dt {
    margin-top: 8px;
    margin-bottom: 12px;
}
```

![Screen Shot of Glossary](https://user-images.githubusercontent.com/116832/148813617-83641f13-96b0-4c38-927b-38fac4a06ab6.png)

**Comment by mgifford** [comment]
@danid123 what do you think of making the top margin smaller? Maybe `margin-top: 6px;`?

**Comment by mgifford** [comment]
That works for me. Do you want to roll up a patch @danid123?
