### ISSUE TITLE
Switch the order of the buttons to preference YAML

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#228]
Possibly eliminate Markdown.

**Comment by dmundra** [comment]
@mgifford if we can eliminate Markdown it would save me time recreating the Markdown output. What do you prefer?

**Comment by mgifford** [comment]
I don't see any reason to include the Markdown version at this stage. I think it just confuses things for non-technical users. 

I just was asking myself what is the situation where a Markdown version would be preferable either to the YAML file or the HTML file?  We don't want folks producing a Markdown file and then editing it to produce Word, PDF or HTML versions..  

Possibly there should just be one button that either downloads 2 files or 1 zip with 2 files in it.

If there is going to be more than one button then it should be very clear visually which one is the most important. We don't want folks to save the wrong one and then not be able to edit their work.

**Comment by dmundra** [comment]
Good questions. I don't think producing a zip file is worth it either for the same reasons and also probably tricky in Svelte because it is running client side. The markdown was tricky enough.

I can remove it when I work on output.
