### ISSUE TITLE
Create warning when folks choose to leave the unsaved editor

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#229]
The WCAG-EM Editor has a good use of this.

@danid123 & I were just talking about how this would be useful.

![Screen Shot of warning message](https://user-images.githubusercontent.com/116832/144668809-7bcde030-f9d7-4bd8-9c39-285715df951a.png)
.

**Comment by dmundra** [comment]
Found the WCAG-EM code and added it the pull request.
