### ISSUE TITLE
Add section 508 colors for buttons and fix email on editor.

### ISSUE THREAD

**Issue by dmundra** [GSA/openacr#231]
Mimic any of the colors from https://www.section508.gov/

**Comment by dmundra** [comment]
GSA/Section508 placeholder styling:
* Dark blue: #162E51 (from https://designsystem.digital.gov/utilities/color/ `text-primary-darker`)
* Light blue: #1e6ad6 (from https://www.section508.gov/buy-sell/ the anchor link color)

**Comment by dmundra** [comment]
@mgifford and @danid123 I documented where I found the new colors from.

**Comment by mgifford** [comment]
Absolutely.  But you've go blue vs blue. Not as good as Red vs. Blue...
https://www.color-hex.com/color/162e51
https://www.color-hex.com/color/1e6ad6

We could have a nice green from Section508.gov
https://www.color-hex.com/color/00A872

or even (also from the same site)
https://www.color-hex.com/color/058850

I don't know. I'm not a color guy. But sometimes there is too much blue....
