### ISSUE TITLE
Comments & notes should be at least a certain length

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#243]
It would be great if authors were given encouragement about adding better descriptions. This can be done by checking length. We can put a recommendation of about 50 characters?

**Comment by mgifford** [comment]
![Screen Shot of potential way to nudge users](https://user-images.githubusercontent.com/116832/146596548-b1967dd7-2579-4c06-9497-ed052c76a883.png)

**Comment by dmundra** [comment]
Quite easy in svelte. I will leave the help text to you @mgifford. You can send me the text and I can add it to the `helpText.yaml` file.

**Comment by mgifford** [comment]
The text you came up with was good. Looks like when we get the ARIA sorted we will be able to easily change the text going ahead in the YAML file too which is great.
