### ISSUE TITLE
Collapse section

### ISSUE THREAD

**Issue by farooqzakhilwal** [GSA/openacr#244]
-Default to all sections collapsed?
-Higher priority.

**Comment by bruce-usab** [comment]
Whatever the default, I am hoping you will have an open all / collapse all function or feature.

In my experience, collapse all is the better (more useful / easier to scan the page) default presentation.  But accordions which need to be opened manually are a barrier to using search (on the page from the browser, site search, Google hits).

Not a priority, but I thought it would be good to mention sooner than later.

**Comment by dmundra** [comment]
Thank you @bruce-usab. We have those buttons on the overview page https://gsa.github.io/openacr-editor. Good feedback about what should be the default. My vote would be collapse all as well.

**Comment by bruce-usab** [comment]
Nice!  You might feedback to USWDS because I think this is still an open issue for them:  https://github.com/uswds/uswds/issues/3654

**Comment by mgifford** [comment]
Someone commented on Twitter, "It would be nice to omit areas that don't pertain to the project."

**Comment by dmundra** [comment]
> Someone commented on Twitter, "It would be nice to omit areas that don't pertain to the project."

On the list to add.

**Comment by dmundra** [comment]
Looks like this was easier than I thought. I wrapped each section in a `details` and the header in `summary`. Also our anchor link styling seems to work fine with the +/- buttons so I think we can leave it for now.

@danid123 when you get a chance please take a look at the site https://gsa.github.io/openacr-editor/ and let me know if the changes from the [pull request](https://github.com/GSA/openacr-editor/pull/21) is working well.

**Comment by mgifford** [comment]
Just took a quick look, but looks good to me.

**Comment by dmundra** [comment]
Thanks @mgifford. I also added skip to content link and improved the anchor link handling on other pages.
