### ISSUE TITLE
Add "none" no selection option for level instead of assuming "Not evaluated" is the none option

### ISSUE THREAD

**Issue by dmundra** [GSA/openacr#246]
From @danid123, "drop-down can start from “none” this will allow “Not evaluated” to also be counted as a valid value."

Also update the progress bar calculation to calculate based on "none".

**Comment by dmundra** [comment]
Researching this I believe I need to update the validator to allow "none" i.e. empty string values because right now I get invalid message.

**Comment by bruce-usab** [comment]
Just adding my two-bits that

1. an explicit value of <q>not evaluated</q> is, in my experience, frequently an important data point
2. i am not clear on the context, but <q>null</q> / <q>empty</q> seems like it might be different from <q>none</q> or <q>n/a</q> and maybe even <q>no selection option</q>

**Comment by dmundra** [comment]
Hi @bruce-usab. For 1. Yes the intention is allow "not evaluated" to be a specific choice. I was previously using it as the default "none" selection. For 2, I am going to introduce the "no selection option" essentially as I was previously naively defaulting to "not evaluated".

Once I get the validator adjusted I will share the editor and share the changes. Thank you for your input.

**Comment by dmundra** [comment]
The changes are live https://gsa.github.io/openacr-editor. Now instead of defaulting to "not evaluated" the level dropdown shows a '- Select -' option which is equal to "". In the report those values are then not show in the row. Eventually I will figure out how to hide the row completely if no level or notes are entered.
