### ISSUE TITLE
Editor template data object error

### ISSUE THREAD

**Issue by danid123** [GSA/openacr#256]
I use Chrome as my primary browser and noticed that a couple of weeks ago the pages of the editor stopped loading for me in Chrome. All the form pages didn't load content. The Editor worked fine in Firefox and in Safari (note I had not previously attempted to view the editor in those browsers).  

I was able to fix the issue for myself by replacing the local storage object in Chrome with the info from Firefox. See the attached screenshots for the error messages.

<img width="1233" alt="Screen Shot 2021-12-27 at 9 08 19 AM" src="https://user-images.githubusercontent.com/4855793/147493036-a1f773d1-0ab3-4c28-8891-77465c3c186d.png">

<img width="673" alt="Screen Shot 2021-12-27 at 9 00 42 AM" src="https://user-images.githubusercontent.com/4855793/147493060-68a7cf41-ecc3-4587-93fa-d4e3493bba2b.png">

<img width="612" alt="Screen Shot 2021-12-27 at 9 01 34 AM" src="https://user-images.githubusercontent.com/4855793/147493084-3436d2a6-f51d-4036-901f-1db168bee30d.png">

**Comment by dmundra** [comment]
Thank you @danid123 for the detailed description and the workaround. I introduced that bug when working on #220 and I believe it is fixed but do let me know if you are still seeing it.

**Comment by dmundra** [comment]
The solution for this is to the increment the data model number so that previous storages are invalidated and you have to load the YAML file again or start a new report.
