### ISSUE TITLE
Eliminate option to download just the HTML page

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#259]
A user should be able to download just the YAML or the YAML file & HTML file.  It shouldn't be an option to just download the HTML because users will loose work. 

Button labels and order:
- Download Report (YAML and HTML files) (blue)
- Download YAML only (outline button)

Can we add the file download icon before the text? 

![Screen Shot with text](https://user-images.githubusercontent.com/116832/148280515-e9b0eea1-9ba6-47b7-b2e3-4afc8bd8c1a4.png)

Note: We should also highlight the colors so that the default (HTML & YAML) is the boldest option on the page. We want to shape defaults people choose.

**Comment by dmundra** [comment]
@danid123 and @mgifford so this one is a challenge. Having one button download two files means we either have to zip it up for them or do some JavaScript code where one button clicks two buttons and downloads two files.

In any case, the [WCAG EM](https://www.w3.org/WAI/eval/report-tool/evaluation/view-report) and ATAG editors suffer from the same concern that the user would only download the HTML file and not remember to download the JSON file (in their case). This is mitigated by the fact that the local storage doesn't disappear unless we update the model (which we will stop doing once we have released a version that is stable) or if the user clears the local storage themselves.

I think we should not download two files with one button as that is behavior that I haven't seen. Zip is an approach but then we might have to support uploading a zip file which I would prefer to avoid.

Can we nudge them to think about the different uses of each file like in the overview instructions or instructions on the report page?

**Comment by mgifford** [comment]
We can definitely push this back to a later sprint if it is complicated.  I was thinking that we'd be able to use something like this to create a zip file with the html/yaml - https://stuk.github.io/jszip/

I wasn't thinking that anyone would upload a zip file though.  The YAML file is the report, HTML is just presentation. Just most folks will want them together.

For now @danid123 what do you think about opening up a new issue to help make a button clearly the default (YAML) file and to create text that reinforces that the YAML file is the one of value.

**Comment by danid123** [comment]
In design apps where exporting certain formats (usually native files) and in software for visualizing data there are buttons that download multiple files and those are usually zipped. I think people would become familiar with it if we mentioned it in the overview. 

The other benefit of a zipped folder is we could include a readme that would explain why there are two files and how to upload them to the OpenACR editor in order to edit for collaboration purposes. Otherwise people would send YAML files and may or may not explain what to do with the file well for the person receiving the file.

**Comment by dmundra** [comment]
@danid123 and @mgifford could you give me the text for the readme file? I was able to get zip download working.

**Comment by dmundra** [comment]
We will updated readme in #273
