### ISSUE TITLE
Change the layout of the Your Report box to one column

### ISSUE THREAD

**Issue by danid123** [GSA/openacr#260]
It would eliminate the problem with the Titles running into the number of sections on smaller screens.

Current
<img width="281" alt="Current Your Report" src="https://user-images.githubusercontent.com/4855793/148262303-edd9c6c3-248b-4a86-838e-3cca1aecb583.png">

Example
<img width="313" alt="Example Your Report" src="https://user-images.githubusercontent.com/4855793/148262441-1b87442a-ddee-4809-974f-eef9b6c6b6ab.png">

**Comment by dmundra** [comment]
Would it be okay if I make the change to one column first before changing the contents for this issue?
