### ISSUE TITLE
Add help text at the top of the page

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#261]
Right now there is no guidance. Nothing is expanded by default. 

There should be guidance about expanding the fields.  Just as a first stab at this I've created something.

![Screen Shot with additional help text](https://user-images.githubusercontent.com/116832/148277434-78290483-214e-4e89-90ee-2ee55caff10c.png)

### About
- Fill in information about product or service being reviewed. This is the base of the report, so please provide as much information as possible.

### Table 1: Success Criteria, Level A
- Provide all Level A errors found through your review of the website. Currently only WCAG 2.0 is supported. Web is assumed, but other fields are available for Documentation, Authoring and Software. Please fill in as appropriate. 

### Table 2: Success Criteria, Level AA
- Provide all Level AA errors found through your review of the website. Currently only WCAG 2.0 is supported. Web is assumed, but other fields are available for Documentation, Authoring and Software. Please fill in as appropriate. 

### Table 3: Success Criteria, Level AAA
- Consider providing Level AAA affordances that your product supports or partially supports. This is optional for most organizations, but may be useful to help determine if your product is a good fit for a specific application. 

### Chapter 3: Functional Performance Criteria (FPC)
- _The FPC may be be auto-populated from WCAG criteria. If barriers are present which cannot be described in other pages, you can include it here_.

### Chapter 4: Hardware
- If this includes hardware, include the Section 508 evaluation. 

### Chapter 5: Software
- Web based software can be described in Tables 1, 2 & 3. Software that is non-web based (native web applications, Windows or Mac applications), can use this Section 508 table to describe them. 

### Chapter 6: Docs
- Documentation is critical for many digital tools. If non-web based documentation is provided (MS Word or PDF files), fill in the following table.

**Comment by danid123** [comment]
### About
Fill out general information about your product or service. Please provide as much detail as possible. The question asking you to describe your product will determine which sections are available to fill out. If you need to change this later, just change your response to this question.

### Table 1: Success Criteria, Level A
Provide information about Level A errors for your website or web application. Currently only WCAG 2.0 is supported. Web-based is assumed, but there are also fields provided for Documentation, Authoring and Software [link to each section].

### Table 2: Success Criteria, Level AA
Provide all Level AA errors found through your review of the website. Currently only WCAG 2.0 is supported. Web is assumed, but other fields are available for Documentation, Authoring and Software. Please fill in as appropriate.

### Table 3: Success Criteria, Level AAA
Consider providing Level AAA affordances that your product supports or partially supports. This is optional for most organizations, but may be useful to help determine if your product is a good fit for a specific application.

### Chapter 3: Functional Performance Criteria (FPC)
The FPC may be be auto-populated from WCAG criteria. If barriers are present which cannot be described in other pages, you can include it here.

### Chapter 4: Hardware
If your product includes hardware, please fill out this section.

### Chapter 5: Software
If your software product is web-based, do not fill out this section. Please fill out Tables 1, 2, and 3 [link to Table 1]. 

If your software product is not web-based, please fill out this section. Examples of non-web-based software include native web applications and desktop applications.

### Chapter 6: Documentation
If the documentation for your product is not web-based (MS Word or PDF files), please fill out this section.

**Comment by mgifford** [comment]
@danid123 I've built on them after running them through the HemingwayApp

## About

Fill out general information about your product or service. Please provide as much detail as possible. By describing your product the webform will update to show only the sections you need to fill out. If you need to change this later, change your response to this question.

## Table 1: Success Criteria, Level A

Provide information about Level A errors for your website or web application. Currently OpenACR only supports WCAG 2.0. The default is web-based, and there are optional fields Documentation, Authoring and Software [link to each section]. Please fill in as appropriate.

## Table 2: Success Criteria, Level AA

Provide information about Level AA errors for your website or web application. Currently OpenACR only supports WCAG 2.0. The default is web-based, and there are optional fields Documentation, Authoring and Software. Please fill in as appropriate.

## Table 3: Success Criteria, Level AAA

Consider providing information about Level AAA affordances for your website or web application. WCAG designed Level AAA as an aspirational goal, so it should always be optional. It is useful to describe how your product or service exceeds AA requirements. Some projects may need specific AAA requirements to meet their needs, so it is good to strive for. 

## Chapter 3: Functional Performance Criteria (FPC)

Describe barriers here if they are not covered in other sections. Highlight the impact on different types of disabilities. 

## Chapter 4: Hardware

If your product includes hardware, please fill out this section.

## Chapter 5: Software

If your software product is web-based, do not fill out this section. Please fill out Tables 1, 2, and 3 [link to Table 1].

If your software product is not web-based, please fill out this section. Desktop applications are a common example of non-web-based software.

## Chapter 6: Documentation

If the documentation for your product is not web-based (MS Word, OpenOffice or PDF files), please fill out this section.

**Comment by dmundra** [comment]
This ticket would be a good one for Jacqueline to work on so let me know when it is ready.

**Comment by mgifford** [comment]
Possible mockup

![Screen Shot of the documentation page](https://user-images.githubusercontent.com/116832/149999737-ffa6c02e-d318-41db-84b8-e0bb02d651dd.png)

**Comment by dmundra** [comment]
@qjac this is ready to go. Mike's last two comment are the text and the possible location of it.

**Comment by mgifford** [comment]
Also @qjac we also had feedback on this that I incorporated, and this is the latest version of the test we should be running with.

## About
Fill out general information about your product or service. Please provide as much detail as possible. By describing your product the webform will update to show only the sections you need to fill out. If you need to change this later, change your response product information questions.

## Table 1: Success Criteria, Level A
Provide information about Level A isuses with your website or web application. Currently OpenACR only supports WCAG 2.0. The default is web-based, and there are optional fields Documentation, Authoring and Software [link to each section]. Fill out as appropriate.

## Table 2: Success Criteria, Level AA
Provide information about how your website or web application fails to meet Level AA requirements. Currently OpenACR only supports WCAG 2.0. The default is web-based, and there are optional fields Documentation, Authoring and Software. Please fill in as appropriate.

## Table 3: Success Criteria, Level AAA
This section is optional.  Consider providing information about Level AAA support in your website or web application. WCAG Level AAA reflect accessibility features that exceed the minimum requirements of Section 508. It is useful to describe how your product or service exceeds Level AA requirements. Additionally, some end-users and some projects may need specific AAA requirements to be meet.

## Chapter 3: Functional Performance Criteria (FPC)
Describe barriers here if they are not covered in other sections. Highlight the impact on different types of disabilities. Optionally, this section may be used to summarize accessibility features described in more detail elsewhere.

## Chapter 4: Hardware
If the Information and Communications Technology (ICT) includes hardware, please fill out this section.

## Chapter 5: Software
If your software product is a web application or is rendered through a web browser, do not fill out this section. Fill out Tables 1, 2, and 3 [link to Table 1]. Fill out this section if your software product is not web-based. Desktop applications are a common example of software which is not web-based.  Software which uses internet communication but is not used via a third-party web browser (e.g., Chrome, Edge, Safari), is not web-based software.

## Chapter 6: Support Documentation and Services
If the support documentation for your product is not web-based (e.g., MS Word, OpenOffice or PDF files), fill out this section.

**Comment by qjac** [comment]
"Documentation, Authoring and Software [link to each section]"
What urls should each of those link to?

**Comment by mgifford** [comment]
Think we're looking at these:
https://gsa.github.io/openacr-editor/chapter/success_criteria_level_a#1.1.1-electronic-docs-editor
https://gsa.github.io/openacr-editor/chapter/success_criteria_level_aa#1.2.4-electronic-docs-editor

But relative URLs.

**Comment by qjac** [comment]
@danid123 @mgifford Is this sentence missing a word? It reads awkwardly to me.

"The default is web-based, and there are optional fields Documentation, Authoring and Software."

**Comment by mgifford** [comment]
This makes more sense:
"The default is web-based, and there are optional fields for Documentation, Authoring and Software."


Thanks. Always useful to run software through a grammar checker...

**Comment by qjac** [comment]
"If you need to change this later, change your response product information questions." From the About section. Is this line missing a word or two? @mgifford @danid123
