### ISSUE TITLE
Change the Notes label to Remarks and Explanations to encourage users to fill it out

### ISSUE THREAD

**Issue by danid123** [GSA/openacr#263]

**Comment by dmundra** [comment]
Also noticed that we don't support markdown like we say in the overview page so I can fix that bug at the time this is changed. @danid123 let me know when this is ready to be worked on.

**Comment by dmundra** [comment]
I just realized in the report table we do say 'Remarks and Explanations' as the column heading 🤦🏾 . So I will make this change.
