### ISSUE TITLE
Disable irrelevant sections for the user

### ISSUE THREAD

**Issue by danid123** [GSA/openacr#265]
- [x] Add checkboxes in About to disable which sections the user needs to fill out.
- [x] When checked the fields on those pages are disabled but the user can still fill out notes at the top.
- [x] The user is shown the disable/enable checkbox on the page as well and they can uncheck it to re-enable the fields.
- [x] On the report page any disabled sections will have the tables be hidden from the HTML but still show the title and any notes.
- [x] Add copy in the About that explains this is what is happening.

Separate ticket for "Add a bullet point to the Overview that explains that we will disable sections based on how the user answers."

**Comment by mgifford** [comment]
This might look like this:

![WCAG ACR elements](https://user-images.githubusercontent.com/116832/148272905-ce20f4d5-daff-4202-83c0-a938c0bafac3.png)

![ACR elements](https://user-images.githubusercontent.com/116832/148273946-c3bfa999-6351-4b2c-aaec-f9cf9f8690eb.png)

**Comment by danid123** [comment]
The labels should match the navigation labels/page headings:
- [ ] Web 
    - [ ] A
    - [ ] AA
    - [ ] AAA
- [ ] Functional Performance Criteria (FPC)
- [ ] Hardware 
- [ ] Software
- [ ] Support Documentation and Services

Can the A levels only show appear once Web is selected?

**Comment by mgifford** [comment]
I'm actually wondering if we should build it so that web is the only check box. A & AA will always be required with web. There is no ACR right that I know of that is looking for single A. AAA is always just optional, but I don't know if we should bother enabling/disabling it. 

- [ ] Web (A, AA and AAA)
- [ ] Functional Performance Criteria (FPC)
- [ ] Hardware 
- [ ] Software
- [ ] Support Documentation and Services

**Comment by dmundra** [comment]
My two cents here is that this change is going to large for code to handle hiding sections so I think once you have a desired approach then we can either create a ticket for implementation or move this to the sprint where we want to implement this.

**Comment by dmundra** [comment]
Made on progress on this. Created a storage place to track the values of the checkboxes separate from the OpenACR evaluation.

**Comment by dmundra** [comment]
@danid123 and @mgifford I need a [review of the help text I added](https://github.com/GSA/openacr-editor/pull/37/files#diff-5cc51f2b30eb0ead3c95abdac33b5cdc8f11f4bf5be3628615a5cbb994733b18R36) and then new text for the overview page. I can also create a separate ticket is that is better.

**Comment by dmundra** [comment]
Thanks @danid123 closing this ticket as a new one will focus on content.
