### ISSUE TITLE
Report date, version number, and last edited date of the ACR document

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#269]
@danid123 & I were talking and I think we need a version number field on the About page.  We can't trust that users will get this right.  We can also ensure that when we save the version number. 

Right now we just use the name & version of the software:
  drupal-9.1.yaml

This probably should be:
  drupal-9.1-3.yaml

Given that we've had a few other "releases" previous to this.

If I'm creating a OpenACR file from scratch the default version number for the document should be 1.  If I load and then save the document, the user should be prompted if they want to update the version number.  

This also should show up in the HTML report near the date.

It's a bit crude, but might be the best way to avoid confusion when people ship ACRs back/forth between each other.

**Comment by danid123** [comment]
Is this related to the idea of a last edited date?

**Comment by mgifford** [comment]
This is independent of the last edited date.  I like the idea of having both.  I'm not even sure that we want to allow the editor to change the value. We can just save that and display it as read-only... somewhere..

**Comment by danid123** [comment]
I like the idea of not letting the editor to change the value. So does that mean we'd have:
- Report date (set by user)
- Report version (auto generated)
- Last edited date (auto generated)

**Comment by danid123** [comment]
Here is a mock of how the fields should look. @mgifford @dmundra do you think it's clear that the fields are read-only? I also tried having the fields be a little bit darker but I felt that decreased the contrast too much.
![Editor - About](https://user-images.githubusercontent.com/4855793/154233909-85d9c3a7-972a-44bb-9059-4e3494df28d9.png)
<img width="777" alt="Screen Shot 2022-02-16 at 1 22 46 AM" src="https://user-images.githubusercontent.com/4855793/154234502-b1991242-e526-4ea8-a734-7925d08ace55.png">

**Comment by mgifford** [comment]
I like it! We'd just make them readonly by `<input type="text" readonly="readonly" />`

**Comment by dmundra** [comment]
@danid123 and @mgifford I am going to add the two new fields (last modified date and version) to the schema so we store them in the YAML file. In the display on the report just place it below the report date I presume? Maybe not version but we could add that as well. Thoughts?

**Comment by danid123** [comment]
@dmundra I was on the fence about adding the version but I think if we don't display it anywhere in the UI, that the updating version in the filename would be confusing to users.

**Comment by dmundra** [comment]
Agreed. I will find a useful spot for it.

**Comment by dmundra** [comment]
Also I am going to store version as an integer so I can easily increment but in the field and report I will display it concatenated with the product version.

**Comment by dmundra** [comment]
Also changing the help text to 'Version is a read-only field that is automatically updated when report is uploaded.' Following @mgifford original comment, that is when the user starts a new report they start with 1 and then they download it with `version=1` saved. When they upload it then the editor increment the version to 2 and so on. I think that is the easiest way to update the version.

As for 'last modified date' I update that whenever any field is changed but that is not an issue because it will just update the date to today's date and keep doing that while doing that for the version would mean it would keep counting up.

**Comment by dmundra** [comment]
As for report output, how about this:

![Screenshot of dates on report page](https://user-images.githubusercontent.com/7096681/154377900-773d752b-6ac9-4cf7-b5e0-5d5ca9361852.png)

**Comment by danid123** [comment]
@dmundra that looks good to me
