### ISSUE TITLE
Onboarding new team member

### ISSUE THREAD

**Issue by dmundra** [GSA/openacr#274]
For onboarder

- [x] Get GitHub username: https://github.com/qjac
- [x] Add to the three repos.
- [x] Share links to repos, issues, project board, wiki, UX links.
- [x] Setup call to review the links and if working on the tools on how they are set up.
- [x] Find a ticket that can be worked on my new team member.

For new team member

- [x] Review links.
- [x] Attend meeting.
- [x] If working on the tools, download and get them running locally (check that the site or CLI is working and the tests are running).
- [x] Install [pre-commit](https://github.com/GSA/openacr/wiki/Dependencies#pre-commit) and enable it locally for each repo.
- [x] Review [pull request creation and review](https://github.com/GSA/openacr/wiki/Pull-request-creation-and-review) wiki page.
- [x] Share any roadblocks, issues, ideas with onboarder. Create issues if needed.
- [x] Work on the ticket assigned. Ask questions and reach out as needed.

**Comment by dmundra** [comment]
Current list of links:
Repos:

- https://github.com/GSA/openacr: Validator tool source (Typescript/JavaScript). Also our primary space where we [track issues](https://github.com/GSA/openacr/issues), have our [project board](https://github.com/GSA/openacr/projects/1) and [wiki](https://github.com/GSA/openacr/wiki).
- https://github.com/GSA/openacr-website: Static website source (Jekyll) where we will be publishing the project details and roadmap. No live URL yet, [current test URL](https://federalist-6d3494a6-5b03-42fa-82f2-57f3bbb203af.app.cloud.gov/site/gsa/openacr-website/).
- https://github.com/GSA/openacr-editor: Editor tool source (Svelte/JavaScript). No live URL yet, [current test URL](https://gsa.github.io/openacr-editor).

UX:

- [Service Design Blueprint](https://app.mural.co/t/civicactions3117/m/civicactions3117/1638499582182/4d28df29dfc20a10faa83dca1682b98c963be11c?sender=u25a05567b17798ca9e655031)
- [Stakeholder Map](https://docs.google.com/document/d/1UxaJoyRBVvHh9q7XcIfhQ65eyaAOECXSF8_goMg2kdg/edit?usp=sharing)

**Comment by dmundra** [comment]
Meeting agenda:
* Review the technical details of each repo and how each app works.
* Review the issue/project board process.
* Review the pull request process and how tests run.
* Review the deploy project.

**Comment by dmundra** [comment]
Two potential tickets to work on:
- #261 
- #273

**Comment by qjac** [comment]
- [x]  Review links.
- [x]  Attend meeting.
- [x]  If working on the tools, download and get them running locally (check that the site or CLI is working and the tests are running).
- [x]  Install pre-commit and enable it locally for each repo.
- [x]  Review pull request creation and review wiki page.
- [ ]  Share any roadblocks, issues, ideas with onboarder. Create issues if needed.
- [ ]  Work on the ticket assigned. Ask questions and reach out as needed.

**Comment by dmundra** [comment]
@qjac can you confirm you got the invite and accepted it?

**Comment by dmundra** [comment]
@qjac, got your first ticket merged 🎉  so I am going to close this one if you agree.

**Comment by qjac** [comment]
@dmundra that works for me!
