### ISSUE TITLE
Change Docs to Documentation in the top navigation.

### ISSUE THREAD

**Issue by danid123** [GSA/openacr#275]
<img width="781" alt="Screen Shot 2022-01-14 at 10 56 06 AM" src="https://user-images.githubusercontent.com/4855793/149570026-ee9b14f7-f57c-41e1-9132-5c2890e05670.png">

**Comment by qjac** [comment]
PR is in for this text change. Please let me know if my git workflow is good (branch, commit messages, PR messages, etc).

**Comment by dmundra** [comment]
Hi @qjac, I left a comment on the PR but will mention it here.

> @qjac, agreed with Mike changes are looking good. If you can please add the issue URL to the description and if you have any QA steps outside what Mike suggested. Also feel free to merge this after approval.
