### ISSUE TITLE
Add text to the below the download buttons to explain what to do if you can't download zip files

### ISSUE THREAD

**Issue by danid123** [GSA/openacr#279]
<img width="1073" alt="Screen Shot 2022-01-18 at 11 52 10 AM" src="https://user-images.githubusercontent.com/4855793/150008839-41a8fda8-1ff5-4130-96b9-47f228d6bfc1.png">

- [x] Add a line below the existing copy on the button.
Download Report (YAML and HTML)
.zip (centered)
- [x] Add the following body copy below the button:
Some agencies and corporations have a policy prohibiting the the download .of zip files. If your organization has a similar rule, you can complete the following steps to get a YAML and HTML file for sharing:
1. Download the YAML only file
2. Right click anywhere on this page and select Save As.
3. Choose a location where you want to save your HTML file.
4. Share the HTML file or folder and the YAML file you previously downloaded with your collaborators.
5. Let your collaborators know that they can view the HTML version of the file and can make edits by going to the OpenACR editor <link> and uploading the YAML file. When they have completed their edits, they must to send you the YAML file but the HTML file is optional.

**Comment by danid123** [comment]
@mgifford does this look ok to you?

**Comment by mgifford** [comment]
Looks good to me.  Thanks @danid123 

Yes, the file size would be an optional thing. These are largely pretty small files. 

In talking to an accessibility agency last week there was discussion about incorporating blockchain into the OpenACR file format. I didn't see that as a big enhancement. Likewise I can't see the need to have a MD5 hash of the files. If at some point OpenACRs get larger though, maybe these would be things to consider.

**Comment by danid123** [comment]
@dmundra It's missing the beginning paragraph, right above the numbered steps:
"Some agencies and corporations have a policy prohibiting the the download .of zip files. If your organization has a similar rule, you can complete the following steps to get a YAML and HTML file for sharing:"

Even though it's kind of redundant I'm wondering if we do one of these options? @mgifford which one do you like best?
![Download Report Buttons - 1](https://user-images.githubusercontent.com/4855793/151273861-f86ea76e-ced4-4a19-81cd-094f3bc00401.png)
![Download Report Buttons - 2](https://user-images.githubusercontent.com/4855793/151273875-2ab3798e-382b-4be4-9ede-8adcc1c2bf8b.png)
![Download Report Buttons - 3](https://user-images.githubusercontent.com/4855793/151273888-9cfd948d-cda5-405b-ad00-43085e9777d8.png)

**Comment by dmundra** [comment]
Oops. Thanks @danid123 for catching that. I will fix that and the button tomorrow (one you have a button choice selected)

**Comment by mgifford** [comment]
I think #2 is best @danid123 


Also I think we don't need to stress about the wording too much as once it is in place we can get feedback from users and tweak it. 

But yes, something like:

Some agencies and corporations have a policy prohibiting the the download .of zip files. **If you cannot download the .zip file** you can download the YAML file by clicking the link above and save the HTML file convenient viewing by:
- Right click anywhere on this page and select Save As.
- Choose a location where you want to save your HTML file.
- Share the HTML file or folder and the YAML file you previously downloaded with your collaborators.
- Let your collaborators know that they can view the HTML version of the file and can make edits by going to the OpenACR editor and uploading the YAML file. When they have completed their edits, they must to send you the YAML file. The HTML file is optional.

**Comment by bruce-usab** [comment]
Thanks so much for adding this extra bit of instruction!
> Some agencies and corporations have a policy prohibiting the the download .of zip files. If your organization has a similar rule, you can complete the following steps to get a YAML and HTML file for sharing...
