### ISSUE TITLE
Change "Electronic Docs" to "Electronic Documents"

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#280]
There is no point in having the short form in this.
![Screen Shot 2022-01-18 at 1 51 35 PM](https://user-images.githubusercontent.com/116832/150000405-3654fc39-70de-448d-80fa-3b449ea0291c.png)

**Comment by dmundra** [comment]
"Electronic Docs" was something I got from VPAT so this would be a good change to make in the catalog and then it would permeate automatically to the editor. Location of the source: https://github.com/GSA/openacr/blob/main/catalog/data/components.yaml#L7

This one will take multiple steps to get there but I will use this as a demo to share updating the validation tool.

**Comment by mitchellevan** [comment]
I believe "Electronic Docs" is short for "Electronic Documents" in this
context, not "Electronic Documentation."

**Comment by mgifford** [comment]
You are right @mitchellevan thanks for catching this https://www.section508.gov/sample-procurement/electronic-documents/

**Comment by dmundra** [comment]
The plan is update this in the catalog, release new minor version of the `@openacr/openacr`, update the package in the editor and the changes should propagate through that.
