### ISSUE TITLE
Remove Markdown Column and Other References

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#287]
Are we still going to be supporting the MD version? It is still possible with the command line, right? 

It is still easier to see files in GitHub in Markdown than HTML, but when the website launches, that will no longer be the case.

Just looking at removing that column here https://federalist-6d3494a6-5b03-42fa-82f2-57f3bbb203af.app.cloud.gov/preview/gsa/openacr-website/refresh-openacr-table-pa11y-ci-update/openacr/

<img width="1067" alt="Screen Shot of the table with the Markdown column" src="https://user-images.githubusercontent.com/116832/150556915-abb2fee1-365c-4dd5-80db-67ca3fef8f87.png">

**Comment by danid123** [comment]
While we're changing the columns can we: 

- Rename the label of the Title column to ACR
- Rename the VPAT version column to VPAT Version
- Move the OpenACR column to second 

The new column title/order would be ACR, OpenACR, Product/Version, Description, VPAT Version

If the purpose of the table is to allow people to compare ACR with OpenACR it makes sense to put them next to each other. What do you think @mgifford ?

**Comment by mgifford** [comment]
Basically yes. Like these changes.

Keeping the most important information on the left of the table I'd put it in this order though:
Title, Description, Product/Version, OpenACR

I'm thinking we should drop the VPAT Version (previously known as Version). I also think we should have OpenACR continue to be a link to the YAML file, but also show the version of the YAML file, version of the report or maybe even the date.  We will be collecting more information here that may be more relevant in the table.

**Comment by dmundra** [comment]
Here is a screenshot of the report page based on @mgifford's comment. I changed the link for the OpenACR to mention the filename right now which includes the version.

![screenshot of report page](https://user-images.githubusercontent.com/7096681/151231100-5ae71821-96dd-4185-a0ba-f9ff6535c5ad.png)

Changes to that?

**Comment by danid123** [comment]
@dmundra That looks great! I think @mgifford 's changes make the table more focused which is always a good thing when we're trying to not overwhelm readers.
