### ISSUE TITLE
Fix inconsistency with the link to Table 1,2,3 in the help text for Chapter 5

### ISSUE THREAD

**Issue by danid123** [GSA/openacr#290]
The link to go to Table 1, 2, 3 in Chapter 5: Software help text will trigger a "If you leave, you may lose your work" pop-up if you're in the process of filling out your report and only have a few fields filled in. It doesn't actually clear the fields but it might scare users into thinking they lost their data. 

It doesn't trigger the pop up if you load an existing completed report, then click the link (I used the drupal-9 one)

**Comment by qjac** [comment]
Just had this happen in Firefox during a dev hot reload on the AA page. All of the info was still there, but the alert popped up on page reload.
