### ISSUE TITLE
Collapse All/Expand All 'stick' when accordions are manually opened/closed

### ISSUE THREAD

**Issue by qjac** [GSA/openacr#296]
Collapse all seems to stick sometimes when a detail is manually opened.

Tested in chrome and firefox. If I manually expand sections, the 'collapse all' continues to have a strikethru and does not close the open drawers when pressed.

The reverse is also an issue. If I press expand all, but then close some manually, 'expand all' stays disabled.

Screenshot of the disabled 'close all' button and an open details pane. And the reverse.
<img width="876" alt="Screen Shot 2022-01-27 at 3 58 39 PM" src="https://user-images.githubusercontent.com/11020538/151451722-abaa365a-dabb-478f-ae65-0664601ed93b.png">
<img width="774" alt="Screen Shot 2022-01-27 at 4 03 45 PM" src="https://user-images.githubusercontent.com/11020538/151451728-7fed4a60-ddfa-40e5-b09a-c06a96a33f0a.png">

**Comment by dmundra** [comment]
The solution for this was to replace the addEventListener to use the 'toggle' event type instead of the click behavior to update the status of the buttons. Here is the link about the 'toggle' event type https://developer.mozilla.org/en-US/docs/Web/API/HTMLDetailsElement/toggle_event
