### ISSUE TITLE
Put "Can't download the .zip" message into an accordion 

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#298]
This is great text:

> Some agencies and corporations have a policy prohibiting the the download .of zip files. If you cannot download the .zip file you can download the YAML file by clicking the link above and save the HTML file convenient viewing by:
> 
> - Right click anywhere on this page and select Save As.
> - Choose a location where you want to save your HTML file.
> - Share the HTML file or folder and the YAML file you previously downloaded with your collaborators.
> - Let your collaborators know that they can view the HTML version of the file and can make edits by going to the OpenACR editor and uploading the YAML file. When they have completed their edits, they must to send you the YAML file. The HTML file is optional.

But it should be in an accordion that maybe has button text of "Have trouble downloading .zip files?"

**Comment by bruce-usab** [comment]
Thanks so much for making help text for this possible difficulty!
