### ISSUE TITLE
Set up search on website

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#302]
Just looked at what the [USWDS Search gave me in the preview](https://federalist-6d3494a6-5b03-42fa-82f2-57f3bbb203af.app.cloud.gov/site/gsa/openacr-website/search/?utf8=✓&affiliate=federalist-uswds-example&query=vpat). 

We need to:

- Create an account with Search.gov at https://search.usa.gov/signup
- Go to the "Activate" section and get "API Access Key"
- Open _config.yml and look for searchgov fields
- Add your affiliate and access_key
- Your results will not show up immediately. Make sure you follow instructions to index your site.

This will need to happen about the same time we get the subdomain for this site.

**Comment by dmundra** [comment]
Does this need a domain first?

**Comment by mgifford** [comment]
I think so @dmundra

**Comment by mgifford** [comment]
I think we can close this for now. Can re-open it if we decide to launch this on a sub-site.
