### ISSUE TITLE
Fix search button so that the icon shows

### ISSUE THREAD

**Issue by mgifford** [GSA/openacr#303]
The search icon isn't showing up here:
`<button class="usa-button" type="submit"><span class="usa-sr-only">Search</span></button>`

<img width="655" alt="Screen Shot of header with broken image" src="https://user-images.githubusercontent.com/116832/151826338-ede778dd-50c1-4faf-90ce-35c5993aad0c.png">

This I think should be delivered with:

```
@media (min-width: 480px)
.usa-search--small [type="submit"], .usa-search--small .usa-search__submit {
    background-image: url(../uswds/img/usa-icons-bg/search--white.svg), linear-gradient(transparent, transparent);
    background-repeat: no-repeat;
    background-position: center center;
    background-size: 1.3333333333rem;
    width: 2.6666666667rem;
```

When looking at https://18f.gsa.gov/

<img width="605" alt="Screen Shot from 18F's home page" src="https://user-images.githubusercontent.com/116832/151827438-b709e646-f56c-4eb4-a568-087d06525541.png">

**Comment by bruce-usab** [comment]
May be related to https://github.com/uswds/uswds/issues/4478 which we recently resolved at USAB.  Also ping to @michaelhortongsa since Section508.gov is doing the same thing with the How You Know drop-down.

**Comment by mgifford** [comment]
Thanks for the heads-up @bruce-usab 

I wonder if this was broken as part of the[ upgrade we did at the start of the year](https://github.com/GSA/openacr-website/pull/36).

Looks like we'll need to install this:
https://github.com/uswds/uswds-compile#installation

[Demo site can be found here.](https://federalist-6d3494a6-5b03-42fa-82f2-57f3bbb203af.app.cloud.gov/site/gsa/openacr-website/)

**Comment by dmundra** [comment]
Installing all those assets seems like a waste right now. I went ahead and just fixed the code and CSS.
