### ISSUE TITLE
Section508.gov - Strategy for OpenACR

### ISSUE THREAD

**Issue by farooqzakhilwal** [GSA/openacr#307]
Strategy for Section 508 on how to include/showcase OpenACR

**Comment by farooqzakhilwal** [comment]
Mike: What are your thoughts on the subdomain? Would it make sense to have an openacr.section508.gov for a beta site and a openacr-editor.section508.gov for the editor? I’d love to have more oversight on the content for the website we built. More thought will need to be put into how this gets blended into the main section508.gov site.

Other option: to integrate the beta site content into Section508.gov, likely under Section508.gov/buy-sell/ rather than a separate subdomain. If we go that route, then some of the current beta site design would simply need to realign to current Section508.gov layouts. For the editor, would make sense to keep in a separate repo and create new subdomain.

**Comment by danid123** [comment]
@saz33m @drewnielson If the website content is going to be under buy-sell: 

- The content for procurement officers could get buried on the Request Accessibility Info page. 
- It's not entirely clear that this is something new. 
- The current Section508 page is written from the point of view of completing a task for a specific audience of procurement officers. The way we were thinking of OpenACR is more multisided and would feature information for a variety of roles. Everyone from procurement officers to accessibility advocates to people with disabilities who would use the products purchased. And our content is written less from a task-based point of view and more from a collaboration standpoint. It would require quite a bit of restructuring to incorporate all of the roles into the existing segmented structure.

For sellers, I think at first it would stand side-by-side with the VPAT info and eventually be the only info there, so it has less likelihood to get lost. However, sellers would have limited context.

**Comment by farooqzakhilwal** [comment]
@mgifford @danid123 Please population the recommendation in this document: https://docs.google.com/document/d/1RsV-fF49UMTytW1gjssP3tUI5BhI3JftUiyv98HMwDo/edit#
