### ISSUE TITLE
Need 'Select catalog' explanatory text and instructions on downloading before switching

### ISSUE THREAD

**Issue by dmundra** [GSA/openacr#338]
- Add instructions to download a copy before switching catalogs.
- Add more explanatory text/help text around the catalog switching options.

Follow up from #270

**Comment by dmundra** [comment]
@danid123 here is my suggestion for the popup confirmation when switching catalog:

> This may remove any entered criteria from your ACR that are not in the selected catalog. Download a copy of the report if you have not already. Are you sure that's what you'd like to do?

What do you think?

**Comment by dmundra** [comment]
@danid123 looks like #340 is where most of the work is being done. Can you review my comment above and then close this one?

**Comment by danid123** [comment]
Closing issue and moving to #340
