### ISSUE TITLE
File upload of YAML files on chromebook doesn't work

### ISSUE THREAD

**Issue by dmundra** [GSA/openacr#339]
@mgifford discovered that upload of YAML files on a chromebook does not seem to work. We cannot figure out what the mime-type is either and this line https://github.com/GSA/openacr-editor/blob/main/src/utils/importEvaluation.js#L13 doesn't give an error so that can be improved as well.

**Comment by mgifford** [comment]
This is clearly an upstream bug...  That said, it is an annoying one.

You found a similar issue on in the Chrome bug tracker, right? Best to link to that here I think (even if it isn't quite right).

**Comment by dmundra** [comment]
@mgifford not sure if https://bugs.chromium.org/p/chromium/issues/detail?id=342554 is relevant as it is pretty old. Should we allow the file to go through based on file extension? That seems like the one workaround for now.

**Comment by mgifford** [comment]
If there is no mime type, let's default to the extension to determine the file type.  That seems like the best approach until Google gives us access root access to their repo...
